"""e

Revision ID: a9f4c5d33b28
Revises: d1bc6f287244
Create Date: 2022-07-11 11:34:34.828559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f4c5d33b28'
down_revision = 'd1bc6f287244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
