"""create comment

Revision ID: d1bc6f287244
Revises: 
Create Date: 2022-07-11 10:24:08.764385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1bc6f287244'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('real_estate',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('real_estate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('townships', sa.String(length=100), nullable=True),
    sa.Column('transaction_sign', sa.String(length=128), nullable=True),
    sa.Column('house_number_plate', sa.String(), nullable=True),
    sa.Column('total_area_square_meter', sa.Float(), nullable=True),
    sa.Column('use_zoning', sa.String(), nullable=True),
    sa.Column('non_metropolis_use_district', sa.String(), nullable=True),
    sa.Column('non_metropolis_land_use', sa.String(), nullable=True),
    sa.Column('transaction_year_month_day', sa.Date(), nullable=True),
    sa.Column('transaction_pen_number', sa.String(), nullable=True),
    sa.Column('shifting_level', sa.String(), nullable=True),
    sa.Column('total_floor_number', sa.String(), nullable=True),
    sa.Column('building_state', sa.String(), nullable=True),
    sa.Column('main_use', sa.String(), nullable=True),
    sa.Column('main_building_materials', sa.String(), nullable=True),
    sa.Column('construction_to_complete_the_years', sa.Date(), nullable=True),
    sa.Column('building_shifting_total_area', sa.Float(), nullable=True),
    sa.Column('pattern_room', sa.Integer(), nullable=True),
    sa.Column('pattern_hall', sa.Integer(), nullable=True),
    sa.Column('pattern_health', sa.Integer(), nullable=True),
    sa.Column('pattern_compartmented', sa.Boolean(), nullable=False),
    sa.Column('manages_the_organization', sa.Boolean(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('the_unit_price', sa.Integer(), nullable=True),
    sa.Column('the_berth_category', sa.String(), nullable=True),
    sa.Column('berth_shifting_total_area_square_meter', sa.Float(), nullable=True),
    sa.Column('the_berth_total_price', sa.Integer(), nullable=True),
    sa.Column('the_note', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('main_building_area', sa.Float(), nullable=True),
    sa.Column('auxiliary_building_area', sa.Float(), nullable=True),
    sa.Column('balcony_area', sa.Float(), nullable=True),
    sa.Column('elevator', sa.String(), nullable=True),
    sa.Column('transfer_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('real_estate_id', name=op.f('pk_real_estate'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('real_estate')
    # ### end Alembic commands ###
